
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  MemberProfile: 'MemberProfile',
  Event: 'Event',
  Match: 'Match',
  Tournament: 'Tournament',
  TournamentPosition: 'TournamentPosition',
  Payment: 'Payment',
  Expense: 'Expense',
  GalleryItem: 'GalleryItem',
  Participant: 'Participant'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const MemberProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  phone: 'phone',
  email: 'email',
  bloodGroup: 'bloodGroup',
  jerseySize: 'jerseySize',
  jerseyNumber: 'jerseyNumber',
  address: 'address',
  joiningDate: 'joiningDate',
  photoUrl: 'photoUrl',
  teamCategory: 'teamCategory',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MemberProfileScalarFieldEnum = (typeof MemberProfileScalarFieldEnum)[keyof typeof MemberProfileScalarFieldEnum]


export const EventScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  eventDate: 'eventDate',
  location: 'location',
  type: 'type',
  budget: 'budget',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type EventScalarFieldEnum = (typeof EventScalarFieldEnum)[keyof typeof EventScalarFieldEnum]


export const MatchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  opponent: 'opponent',
  matchDate: 'matchDate',
  location: 'location',
  matchType: 'matchType',
  result: 'result',
  score: 'score',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MatchScalarFieldEnum = (typeof MatchScalarFieldEnum)[keyof typeof MatchScalarFieldEnum]


export const TournamentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  startDate: 'startDate',
  endDate: 'endDate',
  location: 'location',
  entryFee: 'entryFee',
  totalPrize: 'totalPrize',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TournamentScalarFieldEnum = (typeof TournamentScalarFieldEnum)[keyof typeof TournamentScalarFieldEnum]


export const TournamentPositionScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  position: 'position',
  teamName: 'teamName',
  prize: 'prize',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TournamentPositionScalarFieldEnum = (typeof TournamentPositionScalarFieldEnum)[keyof typeof TournamentPositionScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  purpose: 'purpose',
  description: 'description',
  paymentDate: 'paymentDate',
  month: 'month',
  year: 'year',
  status: 'status',
  eventId: 'eventId',
  matchId: 'matchId',
  tournamentId: 'tournamentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const ExpenseScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  category: 'category',
  description: 'description',
  expenseDate: 'expenseDate',
  eventId: 'eventId',
  matchId: 'matchId',
  tournamentId: 'tournamentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExpenseScalarFieldEnum = (typeof ExpenseScalarFieldEnum)[keyof typeof ExpenseScalarFieldEnum]


export const GalleryItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  imageUrl: 'imageUrl',
  description: 'description',
  eventId: 'eventId',
  matchId: 'matchId',
  tournamentId: 'tournamentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GalleryItemScalarFieldEnum = (typeof GalleryItemScalarFieldEnum)[keyof typeof GalleryItemScalarFieldEnum]


export const ParticipantScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  eventId: 'eventId',
  matchId: 'matchId',
  tournamentId: 'tournamentId',
  status: 'status',
  joinedAt: 'joinedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ParticipantScalarFieldEnum = (typeof ParticipantScalarFieldEnum)[keyof typeof ParticipantScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

