services:
  db:
    image: postgres:16
    container_name: fff_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: FFFClubManagement
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d FFFClubManagement"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: fff_frontend_app
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./.env.production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: