
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model MemberProfile
 * 
 */
export type MemberProfile = Prisma.MemberProfileModel
/**
 * Model Event
 * 
 */
export type Event = Prisma.EventModel
/**
 * Model Match
 * 
 */
export type Match = Prisma.MatchModel
/**
 * Model Tournament
 * 
 */
export type Tournament = Prisma.TournamentModel
/**
 * Model TournamentPosition
 * 
 */
export type TournamentPosition = Prisma.TournamentPositionModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Expense
 * 
 */
export type Expense = Prisma.ExpenseModel
/**
 * Model GalleryItem
 * 
 */
export type GalleryItem = Prisma.GalleryItemModel
/**
 * Model Participant
 * 
 */
export type Participant = Prisma.ParticipantModel
