
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TeamCategory = {
  JUNIOR: 'JUNIOR',
  SENIOR: 'SENIOR',
  GUEST: 'GUEST'
} as const

export type TeamCategory = (typeof TeamCategory)[keyof typeof TeamCategory]
