
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Match` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Match
 * 
 */
export type MatchModel = runtime.Types.Result.DefaultSelection<Prisma.$MatchPayload>

export type AggregateMatch = {
  _count: MatchCountAggregateOutputType | null
  _min: MatchMinAggregateOutputType | null
  _max: MatchMaxAggregateOutputType | null
}

export type MatchMinAggregateOutputType = {
  id: string | null
  name: string | null
  opponent: string | null
  matchDate: Date | null
  location: string | null
  matchType: string | null
  result: string | null
  score: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MatchMaxAggregateOutputType = {
  id: string | null
  name: string | null
  opponent: string | null
  matchDate: Date | null
  location: string | null
  matchType: string | null
  result: string | null
  score: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MatchCountAggregateOutputType = {
  id: number
  name: number
  opponent: number
  matchDate: number
  location: number
  matchType: number
  result: number
  score: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MatchMinAggregateInputType = {
  id?: true
  name?: true
  opponent?: true
  matchDate?: true
  location?: true
  matchType?: true
  result?: true
  score?: true
  createdAt?: true
  updatedAt?: true
}

export type MatchMaxAggregateInputType = {
  id?: true
  name?: true
  opponent?: true
  matchDate?: true
  location?: true
  matchType?: true
  result?: true
  score?: true
  createdAt?: true
  updatedAt?: true
}

export type MatchCountAggregateInputType = {
  id?: true
  name?: true
  opponent?: true
  matchDate?: true
  location?: true
  matchType?: true
  result?: true
  score?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MatchAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Match to aggregate.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Matches
  **/
  _count?: true | MatchCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MatchMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MatchMaxAggregateInputType
}

export type GetMatchAggregateType<T extends MatchAggregateArgs> = {
      [P in keyof T & keyof AggregateMatch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMatch[P]>
    : Prisma.GetScalarType<T[P], AggregateMatch[P]>
}




export type MatchGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MatchWhereInput
  orderBy?: Prisma.MatchOrderByWithAggregationInput | Prisma.MatchOrderByWithAggregationInput[]
  by: Prisma.MatchScalarFieldEnum[] | Prisma.MatchScalarFieldEnum
  having?: Prisma.MatchScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MatchCountAggregateInputType | true
  _min?: MatchMinAggregateInputType
  _max?: MatchMaxAggregateInputType
}

export type MatchGroupByOutputType = {
  id: string
  name: string
  opponent: string
  matchDate: Date
  location: string | null
  matchType: string
  result: string | null
  score: string | null
  createdAt: Date
  updatedAt: Date
  _count: MatchCountAggregateOutputType | null
  _min: MatchMinAggregateOutputType | null
  _max: MatchMaxAggregateOutputType | null
}

type GetMatchGroupByPayload<T extends MatchGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MatchGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MatchGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MatchGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MatchGroupByOutputType[P]>
      }
    >
  >



export type MatchWhereInput = {
  AND?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  OR?: Prisma.MatchWhereInput[]
  NOT?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  id?: Prisma.StringFilter<"Match"> | string
  name?: Prisma.StringFilter<"Match"> | string
  opponent?: Prisma.StringFilter<"Match"> | string
  matchDate?: Prisma.DateTimeFilter<"Match"> | Date | string
  location?: Prisma.StringNullableFilter<"Match"> | string | null
  matchType?: Prisma.StringFilter<"Match"> | string
  result?: Prisma.StringNullableFilter<"Match"> | string | null
  score?: Prisma.StringNullableFilter<"Match"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Match"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Match"> | Date | string
  payments?: Prisma.PaymentListRelationFilter
  expenses?: Prisma.ExpenseListRelationFilter
  galleryItems?: Prisma.GalleryItemListRelationFilter
  participants?: Prisma.ParticipantListRelationFilter
}

export type MatchOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  opponent?: Prisma.SortOrder
  matchDate?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  matchType?: Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  payments?: Prisma.PaymentOrderByRelationAggregateInput
  expenses?: Prisma.ExpenseOrderByRelationAggregateInput
  galleryItems?: Prisma.GalleryItemOrderByRelationAggregateInput
  participants?: Prisma.ParticipantOrderByRelationAggregateInput
}

export type MatchWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  OR?: Prisma.MatchWhereInput[]
  NOT?: Prisma.MatchWhereInput | Prisma.MatchWhereInput[]
  name?: Prisma.StringFilter<"Match"> | string
  opponent?: Prisma.StringFilter<"Match"> | string
  matchDate?: Prisma.DateTimeFilter<"Match"> | Date | string
  location?: Prisma.StringNullableFilter<"Match"> | string | null
  matchType?: Prisma.StringFilter<"Match"> | string
  result?: Prisma.StringNullableFilter<"Match"> | string | null
  score?: Prisma.StringNullableFilter<"Match"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Match"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Match"> | Date | string
  payments?: Prisma.PaymentListRelationFilter
  expenses?: Prisma.ExpenseListRelationFilter
  galleryItems?: Prisma.GalleryItemListRelationFilter
  participants?: Prisma.ParticipantListRelationFilter
}, "id">

export type MatchOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  opponent?: Prisma.SortOrder
  matchDate?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  matchType?: Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MatchCountOrderByAggregateInput
  _max?: Prisma.MatchMaxOrderByAggregateInput
  _min?: Prisma.MatchMinOrderByAggregateInput
}

export type MatchScalarWhereWithAggregatesInput = {
  AND?: Prisma.MatchScalarWhereWithAggregatesInput | Prisma.MatchScalarWhereWithAggregatesInput[]
  OR?: Prisma.MatchScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MatchScalarWhereWithAggregatesInput | Prisma.MatchScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Match"> | string
  name?: Prisma.StringWithAggregatesFilter<"Match"> | string
  opponent?: Prisma.StringWithAggregatesFilter<"Match"> | string
  matchDate?: Prisma.DateTimeWithAggregatesFilter<"Match"> | Date | string
  location?: Prisma.StringNullableWithAggregatesFilter<"Match"> | string | null
  matchType?: Prisma.StringWithAggregatesFilter<"Match"> | string
  result?: Prisma.StringNullableWithAggregatesFilter<"Match"> | string | null
  score?: Prisma.StringNullableWithAggregatesFilter<"Match"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Match"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Match"> | Date | string
}

export type MatchCreateInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentCreateNestedManyWithoutMatchInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantCreateNestedManyWithoutMatchInput
}

export type MatchUncheckedCreateInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutMatchInput
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemUncheckedCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantUncheckedCreateNestedManyWithoutMatchInput
}

export type MatchUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUpdateManyWithoutMatchNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUpdateManyWithoutMatchNestedInput
}

export type MatchUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutMatchNestedInput
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUncheckedUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUncheckedUpdateManyWithoutMatchNestedInput
}

export type MatchCreateManyInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MatchUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MatchCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  opponent?: Prisma.SortOrder
  matchDate?: Prisma.SortOrder
  location?: Prisma.SortOrder
  matchType?: Prisma.SortOrder
  result?: Prisma.SortOrder
  score?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MatchMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  opponent?: Prisma.SortOrder
  matchDate?: Prisma.SortOrder
  location?: Prisma.SortOrder
  matchType?: Prisma.SortOrder
  result?: Prisma.SortOrder
  score?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MatchMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  opponent?: Prisma.SortOrder
  matchDate?: Prisma.SortOrder
  location?: Prisma.SortOrder
  matchType?: Prisma.SortOrder
  result?: Prisma.SortOrder
  score?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MatchNullableScalarRelationFilter = {
  is?: Prisma.MatchWhereInput | null
  isNot?: Prisma.MatchWhereInput | null
}

export type MatchCreateNestedOneWithoutPaymentsInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutPaymentsInput, Prisma.MatchUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutPaymentsInput
  connect?: Prisma.MatchWhereUniqueInput
}

export type MatchUpdateOneWithoutPaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutPaymentsInput, Prisma.MatchUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutPaymentsInput
  upsert?: Prisma.MatchUpsertWithoutPaymentsInput
  disconnect?: Prisma.MatchWhereInput | boolean
  delete?: Prisma.MatchWhereInput | boolean
  connect?: Prisma.MatchWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MatchUpdateToOneWithWhereWithoutPaymentsInput, Prisma.MatchUpdateWithoutPaymentsInput>, Prisma.MatchUncheckedUpdateWithoutPaymentsInput>
}

export type MatchCreateNestedOneWithoutExpensesInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutExpensesInput, Prisma.MatchUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutExpensesInput
  connect?: Prisma.MatchWhereUniqueInput
}

export type MatchUpdateOneWithoutExpensesNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutExpensesInput, Prisma.MatchUncheckedCreateWithoutExpensesInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutExpensesInput
  upsert?: Prisma.MatchUpsertWithoutExpensesInput
  disconnect?: Prisma.MatchWhereInput | boolean
  delete?: Prisma.MatchWhereInput | boolean
  connect?: Prisma.MatchWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MatchUpdateToOneWithWhereWithoutExpensesInput, Prisma.MatchUpdateWithoutExpensesInput>, Prisma.MatchUncheckedUpdateWithoutExpensesInput>
}

export type MatchCreateNestedOneWithoutGalleryItemsInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutGalleryItemsInput, Prisma.MatchUncheckedCreateWithoutGalleryItemsInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutGalleryItemsInput
  connect?: Prisma.MatchWhereUniqueInput
}

export type MatchUpdateOneWithoutGalleryItemsNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutGalleryItemsInput, Prisma.MatchUncheckedCreateWithoutGalleryItemsInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutGalleryItemsInput
  upsert?: Prisma.MatchUpsertWithoutGalleryItemsInput
  disconnect?: Prisma.MatchWhereInput | boolean
  delete?: Prisma.MatchWhereInput | boolean
  connect?: Prisma.MatchWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MatchUpdateToOneWithWhereWithoutGalleryItemsInput, Prisma.MatchUpdateWithoutGalleryItemsInput>, Prisma.MatchUncheckedUpdateWithoutGalleryItemsInput>
}

export type MatchCreateNestedOneWithoutParticipantsInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutParticipantsInput, Prisma.MatchUncheckedCreateWithoutParticipantsInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutParticipantsInput
  connect?: Prisma.MatchWhereUniqueInput
}

export type MatchUpdateOneWithoutParticipantsNestedInput = {
  create?: Prisma.XOR<Prisma.MatchCreateWithoutParticipantsInput, Prisma.MatchUncheckedCreateWithoutParticipantsInput>
  connectOrCreate?: Prisma.MatchCreateOrConnectWithoutParticipantsInput
  upsert?: Prisma.MatchUpsertWithoutParticipantsInput
  disconnect?: Prisma.MatchWhereInput | boolean
  delete?: Prisma.MatchWhereInput | boolean
  connect?: Prisma.MatchWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MatchUpdateToOneWithWhereWithoutParticipantsInput, Prisma.MatchUpdateWithoutParticipantsInput>, Prisma.MatchUncheckedUpdateWithoutParticipantsInput>
}

export type MatchCreateWithoutPaymentsInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expenses?: Prisma.ExpenseCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantCreateNestedManyWithoutMatchInput
}

export type MatchUncheckedCreateWithoutPaymentsInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemUncheckedCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantUncheckedCreateNestedManyWithoutMatchInput
}

export type MatchCreateOrConnectWithoutPaymentsInput = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutPaymentsInput, Prisma.MatchUncheckedCreateWithoutPaymentsInput>
}

export type MatchUpsertWithoutPaymentsInput = {
  update: Prisma.XOR<Prisma.MatchUpdateWithoutPaymentsInput, Prisma.MatchUncheckedUpdateWithoutPaymentsInput>
  create: Prisma.XOR<Prisma.MatchCreateWithoutPaymentsInput, Prisma.MatchUncheckedCreateWithoutPaymentsInput>
  where?: Prisma.MatchWhereInput
}

export type MatchUpdateToOneWithWhereWithoutPaymentsInput = {
  where?: Prisma.MatchWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutPaymentsInput, Prisma.MatchUncheckedUpdateWithoutPaymentsInput>
}

export type MatchUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUpdateManyWithoutMatchNestedInput
}

export type MatchUncheckedUpdateWithoutPaymentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUncheckedUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUncheckedUpdateManyWithoutMatchNestedInput
}

export type MatchCreateWithoutExpensesInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantCreateNestedManyWithoutMatchInput
}

export type MatchUncheckedCreateWithoutExpensesInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemUncheckedCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantUncheckedCreateNestedManyWithoutMatchInput
}

export type MatchCreateOrConnectWithoutExpensesInput = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutExpensesInput, Prisma.MatchUncheckedCreateWithoutExpensesInput>
}

export type MatchUpsertWithoutExpensesInput = {
  update: Prisma.XOR<Prisma.MatchUpdateWithoutExpensesInput, Prisma.MatchUncheckedUpdateWithoutExpensesInput>
  create: Prisma.XOR<Prisma.MatchCreateWithoutExpensesInput, Prisma.MatchUncheckedCreateWithoutExpensesInput>
  where?: Prisma.MatchWhereInput
}

export type MatchUpdateToOneWithWhereWithoutExpensesInput = {
  where?: Prisma.MatchWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutExpensesInput, Prisma.MatchUncheckedUpdateWithoutExpensesInput>
}

export type MatchUpdateWithoutExpensesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUpdateManyWithoutMatchNestedInput
}

export type MatchUncheckedUpdateWithoutExpensesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUncheckedUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUncheckedUpdateManyWithoutMatchNestedInput
}

export type MatchCreateWithoutGalleryItemsInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentCreateNestedManyWithoutMatchInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantCreateNestedManyWithoutMatchInput
}

export type MatchUncheckedCreateWithoutGalleryItemsInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutMatchInput
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutMatchInput
  participants?: Prisma.ParticipantUncheckedCreateNestedManyWithoutMatchInput
}

export type MatchCreateOrConnectWithoutGalleryItemsInput = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutGalleryItemsInput, Prisma.MatchUncheckedCreateWithoutGalleryItemsInput>
}

export type MatchUpsertWithoutGalleryItemsInput = {
  update: Prisma.XOR<Prisma.MatchUpdateWithoutGalleryItemsInput, Prisma.MatchUncheckedUpdateWithoutGalleryItemsInput>
  create: Prisma.XOR<Prisma.MatchCreateWithoutGalleryItemsInput, Prisma.MatchUncheckedCreateWithoutGalleryItemsInput>
  where?: Prisma.MatchWhereInput
}

export type MatchUpdateToOneWithWhereWithoutGalleryItemsInput = {
  where?: Prisma.MatchWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutGalleryItemsInput, Prisma.MatchUncheckedUpdateWithoutGalleryItemsInput>
}

export type MatchUpdateWithoutGalleryItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUpdateManyWithoutMatchNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUpdateManyWithoutMatchNestedInput
}

export type MatchUncheckedUpdateWithoutGalleryItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutMatchNestedInput
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutMatchNestedInput
  participants?: Prisma.ParticipantUncheckedUpdateManyWithoutMatchNestedInput
}

export type MatchCreateWithoutParticipantsInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentCreateNestedManyWithoutMatchInput
  expenses?: Prisma.ExpenseCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemCreateNestedManyWithoutMatchInput
}

export type MatchUncheckedCreateWithoutParticipantsInput = {
  id?: string
  name: string
  opponent: string
  matchDate: Date | string
  location?: string | null
  matchType: string
  result?: string | null
  score?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutMatchInput
  expenses?: Prisma.ExpenseUncheckedCreateNestedManyWithoutMatchInput
  galleryItems?: Prisma.GalleryItemUncheckedCreateNestedManyWithoutMatchInput
}

export type MatchCreateOrConnectWithoutParticipantsInput = {
  where: Prisma.MatchWhereUniqueInput
  create: Prisma.XOR<Prisma.MatchCreateWithoutParticipantsInput, Prisma.MatchUncheckedCreateWithoutParticipantsInput>
}

export type MatchUpsertWithoutParticipantsInput = {
  update: Prisma.XOR<Prisma.MatchUpdateWithoutParticipantsInput, Prisma.MatchUncheckedUpdateWithoutParticipantsInput>
  create: Prisma.XOR<Prisma.MatchCreateWithoutParticipantsInput, Prisma.MatchUncheckedCreateWithoutParticipantsInput>
  where?: Prisma.MatchWhereInput
}

export type MatchUpdateToOneWithWhereWithoutParticipantsInput = {
  where?: Prisma.MatchWhereInput
  data: Prisma.XOR<Prisma.MatchUpdateWithoutParticipantsInput, Prisma.MatchUncheckedUpdateWithoutParticipantsInput>
}

export type MatchUpdateWithoutParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUpdateManyWithoutMatchNestedInput
  expenses?: Prisma.ExpenseUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUpdateManyWithoutMatchNestedInput
}

export type MatchUncheckedUpdateWithoutParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  opponent?: Prisma.StringFieldUpdateOperationsInput | string
  matchDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  matchType?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  score?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutMatchNestedInput
  expenses?: Prisma.ExpenseUncheckedUpdateManyWithoutMatchNestedInput
  galleryItems?: Prisma.GalleryItemUncheckedUpdateManyWithoutMatchNestedInput
}


/**
 * Count Type MatchCountOutputType
 */

export type MatchCountOutputType = {
  payments: number
  expenses: number
  galleryItems: number
  participants: number
}

export type MatchCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payments?: boolean | MatchCountOutputTypeCountPaymentsArgs
  expenses?: boolean | MatchCountOutputTypeCountExpensesArgs
  galleryItems?: boolean | MatchCountOutputTypeCountGalleryItemsArgs
  participants?: boolean | MatchCountOutputTypeCountParticipantsArgs
}

/**
 * MatchCountOutputType without action
 */
export type MatchCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MatchCountOutputType
   */
  select?: Prisma.MatchCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MatchCountOutputType without action
 */
export type MatchCountOutputTypeCountPaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentWhereInput
}

/**
 * MatchCountOutputType without action
 */
export type MatchCountOutputTypeCountExpensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExpenseWhereInput
}

/**
 * MatchCountOutputType without action
 */
export type MatchCountOutputTypeCountGalleryItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GalleryItemWhereInput
}

/**
 * MatchCountOutputType without action
 */
export type MatchCountOutputTypeCountParticipantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParticipantWhereInput
}


export type MatchSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  opponent?: boolean
  matchDate?: boolean
  location?: boolean
  matchType?: boolean
  result?: boolean
  score?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  payments?: boolean | Prisma.Match$paymentsArgs<ExtArgs>
  expenses?: boolean | Prisma.Match$expensesArgs<ExtArgs>
  galleryItems?: boolean | Prisma.Match$galleryItemsArgs<ExtArgs>
  participants?: boolean | Prisma.Match$participantsArgs<ExtArgs>
  _count?: boolean | Prisma.MatchCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["match"]>

export type MatchSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  opponent?: boolean
  matchDate?: boolean
  location?: boolean
  matchType?: boolean
  result?: boolean
  score?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["match"]>

export type MatchSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  opponent?: boolean
  matchDate?: boolean
  location?: boolean
  matchType?: boolean
  result?: boolean
  score?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["match"]>

export type MatchSelectScalar = {
  id?: boolean
  name?: boolean
  opponent?: boolean
  matchDate?: boolean
  location?: boolean
  matchType?: boolean
  result?: boolean
  score?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MatchOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "opponent" | "matchDate" | "location" | "matchType" | "result" | "score" | "createdAt" | "updatedAt", ExtArgs["result"]["match"]>
export type MatchInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payments?: boolean | Prisma.Match$paymentsArgs<ExtArgs>
  expenses?: boolean | Prisma.Match$expensesArgs<ExtArgs>
  galleryItems?: boolean | Prisma.Match$galleryItemsArgs<ExtArgs>
  participants?: boolean | Prisma.Match$participantsArgs<ExtArgs>
  _count?: boolean | Prisma.MatchCountOutputTypeDefaultArgs<ExtArgs>
}
export type MatchIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MatchIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MatchPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Match"
  objects: {
    payments: Prisma.$PaymentPayload<ExtArgs>[]
    expenses: Prisma.$ExpensePayload<ExtArgs>[]
    galleryItems: Prisma.$GalleryItemPayload<ExtArgs>[]
    participants: Prisma.$ParticipantPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    opponent: string
    matchDate: Date
    location: string | null
    matchType: string
    result: string | null
    score: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["match"]>
  composites: {}
}

export type MatchGetPayload<S extends boolean | null | undefined | MatchDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MatchPayload, S>

export type MatchCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MatchFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MatchCountAggregateInputType | true
  }

export interface MatchDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Match'], meta: { name: 'Match' } }
  /**
   * Find zero or one Match that matches the filter.
   * @param {MatchFindUniqueArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MatchFindUniqueArgs>(args: Prisma.SelectSubset<T, MatchFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Match that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MatchFindUniqueOrThrowArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MatchFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MatchFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Match that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchFindFirstArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MatchFindFirstArgs>(args?: Prisma.SelectSubset<T, MatchFindFirstArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Match that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchFindFirstOrThrowArgs} args - Arguments to find a Match
   * @example
   * // Get one Match
   * const match = await prisma.match.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MatchFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MatchFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Matches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Matches
   * const matches = await prisma.match.findMany()
   * 
   * // Get first 10 Matches
   * const matches = await prisma.match.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const matchWithIdOnly = await prisma.match.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MatchFindManyArgs>(args?: Prisma.SelectSubset<T, MatchFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Match.
   * @param {MatchCreateArgs} args - Arguments to create a Match.
   * @example
   * // Create one Match
   * const Match = await prisma.match.create({
   *   data: {
   *     // ... data to create a Match
   *   }
   * })
   * 
   */
  create<T extends MatchCreateArgs>(args: Prisma.SelectSubset<T, MatchCreateArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Matches.
   * @param {MatchCreateManyArgs} args - Arguments to create many Matches.
   * @example
   * // Create many Matches
   * const match = await prisma.match.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MatchCreateManyArgs>(args?: Prisma.SelectSubset<T, MatchCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Matches and returns the data saved in the database.
   * @param {MatchCreateManyAndReturnArgs} args - Arguments to create many Matches.
   * @example
   * // Create many Matches
   * const match = await prisma.match.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Matches and only return the `id`
   * const matchWithIdOnly = await prisma.match.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MatchCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MatchCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Match.
   * @param {MatchDeleteArgs} args - Arguments to delete one Match.
   * @example
   * // Delete one Match
   * const Match = await prisma.match.delete({
   *   where: {
   *     // ... filter to delete one Match
   *   }
   * })
   * 
   */
  delete<T extends MatchDeleteArgs>(args: Prisma.SelectSubset<T, MatchDeleteArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Match.
   * @param {MatchUpdateArgs} args - Arguments to update one Match.
   * @example
   * // Update one Match
   * const match = await prisma.match.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MatchUpdateArgs>(args: Prisma.SelectSubset<T, MatchUpdateArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Matches.
   * @param {MatchDeleteManyArgs} args - Arguments to filter Matches to delete.
   * @example
   * // Delete a few Matches
   * const { count } = await prisma.match.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MatchDeleteManyArgs>(args?: Prisma.SelectSubset<T, MatchDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Matches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Matches
   * const match = await prisma.match.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MatchUpdateManyArgs>(args: Prisma.SelectSubset<T, MatchUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Matches and returns the data updated in the database.
   * @param {MatchUpdateManyAndReturnArgs} args - Arguments to update many Matches.
   * @example
   * // Update many Matches
   * const match = await prisma.match.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Matches and only return the `id`
   * const matchWithIdOnly = await prisma.match.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MatchUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MatchUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Match.
   * @param {MatchUpsertArgs} args - Arguments to update or create a Match.
   * @example
   * // Update or create a Match
   * const match = await prisma.match.upsert({
   *   create: {
   *     // ... data to create a Match
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Match we want to update
   *   }
   * })
   */
  upsert<T extends MatchUpsertArgs>(args: Prisma.SelectSubset<T, MatchUpsertArgs<ExtArgs>>): Prisma.Prisma__MatchClient<runtime.Types.Result.GetResult<Prisma.$MatchPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Matches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchCountArgs} args - Arguments to filter Matches to count.
   * @example
   * // Count the number of Matches
   * const count = await prisma.match.count({
   *   where: {
   *     // ... the filter for the Matches we want to count
   *   }
   * })
  **/
  count<T extends MatchCountArgs>(
    args?: Prisma.Subset<T, MatchCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MatchCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Match.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MatchAggregateArgs>(args: Prisma.Subset<T, MatchAggregateArgs>): Prisma.PrismaPromise<GetMatchAggregateType<T>>

  /**
   * Group by Match.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MatchGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MatchGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MatchGroupByArgs['orderBy'] }
      : { orderBy?: MatchGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MatchGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMatchGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Match model
 */
readonly fields: MatchFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Match.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MatchClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  payments<T extends Prisma.Match$paymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$paymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  expenses<T extends Prisma.Match$expensesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$expensesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExpensePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  galleryItems<T extends Prisma.Match$galleryItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$galleryItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GalleryItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  participants<T extends Prisma.Match$participantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Match$participantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Match model
 */
export interface MatchFieldRefs {
  readonly id: Prisma.FieldRef<"Match", 'String'>
  readonly name: Prisma.FieldRef<"Match", 'String'>
  readonly opponent: Prisma.FieldRef<"Match", 'String'>
  readonly matchDate: Prisma.FieldRef<"Match", 'DateTime'>
  readonly location: Prisma.FieldRef<"Match", 'String'>
  readonly matchType: Prisma.FieldRef<"Match", 'String'>
  readonly result: Prisma.FieldRef<"Match", 'String'>
  readonly score: Prisma.FieldRef<"Match", 'String'>
  readonly createdAt: Prisma.FieldRef<"Match", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Match", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Match findUnique
 */
export type MatchFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match findUniqueOrThrow
 */
export type MatchFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match findFirst
 */
export type MatchFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Matches.
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Matches.
   */
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Match findFirstOrThrow
 */
export type MatchFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Match to fetch.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Matches.
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Matches.
   */
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Match findMany
 */
export type MatchFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter, which Matches to fetch.
   */
  where?: Prisma.MatchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Matches to fetch.
   */
  orderBy?: Prisma.MatchOrderByWithRelationInput | Prisma.MatchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Matches.
   */
  cursor?: Prisma.MatchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Matches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Matches.
   */
  skip?: number
  distinct?: Prisma.MatchScalarFieldEnum | Prisma.MatchScalarFieldEnum[]
}

/**
 * Match create
 */
export type MatchCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * The data needed to create a Match.
   */
  data: Prisma.XOR<Prisma.MatchCreateInput, Prisma.MatchUncheckedCreateInput>
}

/**
 * Match createMany
 */
export type MatchCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Matches.
   */
  data: Prisma.MatchCreateManyInput | Prisma.MatchCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Match createManyAndReturn
 */
export type MatchCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * The data used to create many Matches.
   */
  data: Prisma.MatchCreateManyInput | Prisma.MatchCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Match update
 */
export type MatchUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * The data needed to update a Match.
   */
  data: Prisma.XOR<Prisma.MatchUpdateInput, Prisma.MatchUncheckedUpdateInput>
  /**
   * Choose, which Match to update.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match updateMany
 */
export type MatchUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Matches.
   */
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyInput>
  /**
   * Filter which Matches to update
   */
  where?: Prisma.MatchWhereInput
  /**
   * Limit how many Matches to update.
   */
  limit?: number
}

/**
 * Match updateManyAndReturn
 */
export type MatchUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * The data used to update Matches.
   */
  data: Prisma.XOR<Prisma.MatchUpdateManyMutationInput, Prisma.MatchUncheckedUpdateManyInput>
  /**
   * Filter which Matches to update
   */
  where?: Prisma.MatchWhereInput
  /**
   * Limit how many Matches to update.
   */
  limit?: number
}

/**
 * Match upsert
 */
export type MatchUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * The filter to search for the Match to update in case it exists.
   */
  where: Prisma.MatchWhereUniqueInput
  /**
   * In case the Match found by the `where` argument doesn't exist, create a new Match with this data.
   */
  create: Prisma.XOR<Prisma.MatchCreateInput, Prisma.MatchUncheckedCreateInput>
  /**
   * In case the Match was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MatchUpdateInput, Prisma.MatchUncheckedUpdateInput>
}

/**
 * Match delete
 */
export type MatchDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
  /**
   * Filter which Match to delete.
   */
  where: Prisma.MatchWhereUniqueInput
}

/**
 * Match deleteMany
 */
export type MatchDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Matches to delete
   */
  where?: Prisma.MatchWhereInput
  /**
   * Limit how many Matches to delete.
   */
  limit?: number
}

/**
 * Match.payments
 */
export type Match$paymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Payment
   */
  select?: Prisma.PaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Payment
   */
  omit?: Prisma.PaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentInclude<ExtArgs> | null
  where?: Prisma.PaymentWhereInput
  orderBy?: Prisma.PaymentOrderByWithRelationInput | Prisma.PaymentOrderByWithRelationInput[]
  cursor?: Prisma.PaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PaymentScalarFieldEnum | Prisma.PaymentScalarFieldEnum[]
}

/**
 * Match.expenses
 */
export type Match$expensesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Expense
   */
  select?: Prisma.ExpenseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Expense
   */
  omit?: Prisma.ExpenseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExpenseInclude<ExtArgs> | null
  where?: Prisma.ExpenseWhereInput
  orderBy?: Prisma.ExpenseOrderByWithRelationInput | Prisma.ExpenseOrderByWithRelationInput[]
  cursor?: Prisma.ExpenseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExpenseScalarFieldEnum | Prisma.ExpenseScalarFieldEnum[]
}

/**
 * Match.galleryItems
 */
export type Match$galleryItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GalleryItem
   */
  select?: Prisma.GalleryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GalleryItem
   */
  omit?: Prisma.GalleryItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GalleryItemInclude<ExtArgs> | null
  where?: Prisma.GalleryItemWhereInput
  orderBy?: Prisma.GalleryItemOrderByWithRelationInput | Prisma.GalleryItemOrderByWithRelationInput[]
  cursor?: Prisma.GalleryItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GalleryItemScalarFieldEnum | Prisma.GalleryItemScalarFieldEnum[]
}

/**
 * Match.participants
 */
export type Match$participantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  where?: Prisma.ParticipantWhereInput
  orderBy?: Prisma.ParticipantOrderByWithRelationInput | Prisma.ParticipantOrderByWithRelationInput[]
  cursor?: Prisma.ParticipantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ParticipantScalarFieldEnum | Prisma.ParticipantScalarFieldEnum[]
}

/**
 * Match without action
 */
export type MatchDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Match
   */
  select?: Prisma.MatchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Match
   */
  omit?: Prisma.MatchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MatchInclude<ExtArgs> | null
}
