
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TournamentPosition` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TournamentPosition
 * 
 */
export type TournamentPositionModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentPositionPayload>

export type AggregateTournamentPosition = {
  _count: TournamentPositionCountAggregateOutputType | null
  _avg: TournamentPositionAvgAggregateOutputType | null
  _sum: TournamentPositionSumAggregateOutputType | null
  _min: TournamentPositionMinAggregateOutputType | null
  _max: TournamentPositionMaxAggregateOutputType | null
}

export type TournamentPositionAvgAggregateOutputType = {
  position: number | null
  prize: number | null
}

export type TournamentPositionSumAggregateOutputType = {
  position: number | null
  prize: number | null
}

export type TournamentPositionMinAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  position: number | null
  teamName: string | null
  prize: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentPositionMaxAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  position: number | null
  teamName: string | null
  prize: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentPositionCountAggregateOutputType = {
  id: number
  tournamentId: number
  position: number
  teamName: number
  prize: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TournamentPositionAvgAggregateInputType = {
  position?: true
  prize?: true
}

export type TournamentPositionSumAggregateInputType = {
  position?: true
  prize?: true
}

export type TournamentPositionMinAggregateInputType = {
  id?: true
  tournamentId?: true
  position?: true
  teamName?: true
  prize?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentPositionMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  position?: true
  teamName?: true
  prize?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentPositionCountAggregateInputType = {
  id?: true
  tournamentId?: true
  position?: true
  teamName?: true
  prize?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TournamentPositionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentPosition to aggregate.
   */
  where?: Prisma.TournamentPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPositions to fetch.
   */
  orderBy?: Prisma.TournamentPositionOrderByWithRelationInput | Prisma.TournamentPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TournamentPositions
  **/
  _count?: true | TournamentPositionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TournamentPositionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TournamentPositionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentPositionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentPositionMaxAggregateInputType
}

export type GetTournamentPositionAggregateType<T extends TournamentPositionAggregateArgs> = {
      [P in keyof T & keyof AggregateTournamentPosition]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournamentPosition[P]>
    : Prisma.GetScalarType<T[P], AggregateTournamentPosition[P]>
}




export type TournamentPositionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentPositionWhereInput
  orderBy?: Prisma.TournamentPositionOrderByWithAggregationInput | Prisma.TournamentPositionOrderByWithAggregationInput[]
  by: Prisma.TournamentPositionScalarFieldEnum[] | Prisma.TournamentPositionScalarFieldEnum
  having?: Prisma.TournamentPositionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentPositionCountAggregateInputType | true
  _avg?: TournamentPositionAvgAggregateInputType
  _sum?: TournamentPositionSumAggregateInputType
  _min?: TournamentPositionMinAggregateInputType
  _max?: TournamentPositionMaxAggregateInputType
}

export type TournamentPositionGroupByOutputType = {
  id: string
  tournamentId: string
  position: number
  teamName: string
  prize: number
  createdAt: Date
  updatedAt: Date
  _count: TournamentPositionCountAggregateOutputType | null
  _avg: TournamentPositionAvgAggregateOutputType | null
  _sum: TournamentPositionSumAggregateOutputType | null
  _min: TournamentPositionMinAggregateOutputType | null
  _max: TournamentPositionMaxAggregateOutputType | null
}

type GetTournamentPositionGroupByPayload<T extends TournamentPositionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentPositionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentPositionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentPositionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentPositionGroupByOutputType[P]>
      }
    >
  >



export type TournamentPositionWhereInput = {
  AND?: Prisma.TournamentPositionWhereInput | Prisma.TournamentPositionWhereInput[]
  OR?: Prisma.TournamentPositionWhereInput[]
  NOT?: Prisma.TournamentPositionWhereInput | Prisma.TournamentPositionWhereInput[]
  id?: Prisma.StringFilter<"TournamentPosition"> | string
  tournamentId?: Prisma.StringFilter<"TournamentPosition"> | string
  position?: Prisma.IntFilter<"TournamentPosition"> | number
  teamName?: Prisma.StringFilter<"TournamentPosition"> | string
  prize?: Prisma.FloatFilter<"TournamentPosition"> | number
  createdAt?: Prisma.DateTimeFilter<"TournamentPosition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentPosition"> | Date | string
  tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
}

export type TournamentPositionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  teamName?: Prisma.SortOrder
  prize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tournament?: Prisma.TournamentOrderByWithRelationInput
}

export type TournamentPositionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TournamentPositionWhereInput | Prisma.TournamentPositionWhereInput[]
  OR?: Prisma.TournamentPositionWhereInput[]
  NOT?: Prisma.TournamentPositionWhereInput | Prisma.TournamentPositionWhereInput[]
  tournamentId?: Prisma.StringFilter<"TournamentPosition"> | string
  position?: Prisma.IntFilter<"TournamentPosition"> | number
  teamName?: Prisma.StringFilter<"TournamentPosition"> | string
  prize?: Prisma.FloatFilter<"TournamentPosition"> | number
  createdAt?: Prisma.DateTimeFilter<"TournamentPosition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentPosition"> | Date | string
  tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
}, "id">

export type TournamentPositionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  teamName?: Prisma.SortOrder
  prize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TournamentPositionCountOrderByAggregateInput
  _avg?: Prisma.TournamentPositionAvgOrderByAggregateInput
  _max?: Prisma.TournamentPositionMaxOrderByAggregateInput
  _min?: Prisma.TournamentPositionMinOrderByAggregateInput
  _sum?: Prisma.TournamentPositionSumOrderByAggregateInput
}

export type TournamentPositionScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentPositionScalarWhereWithAggregatesInput | Prisma.TournamentPositionScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentPositionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentPositionScalarWhereWithAggregatesInput | Prisma.TournamentPositionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TournamentPosition"> | string
  tournamentId?: Prisma.StringWithAggregatesFilter<"TournamentPosition"> | string
  position?: Prisma.IntWithAggregatesFilter<"TournamentPosition"> | number
  teamName?: Prisma.StringWithAggregatesFilter<"TournamentPosition"> | string
  prize?: Prisma.FloatWithAggregatesFilter<"TournamentPosition"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentPosition"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentPosition"> | Date | string
}

export type TournamentPositionCreateInput = {
  id?: string
  position: number
  teamName: string
  prize?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  tournament: Prisma.TournamentCreateNestedOneWithoutPositionsInput
}

export type TournamentPositionUncheckedCreateInput = {
  id?: string
  tournamentId: string
  position: number
  teamName: string
  prize?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentPositionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  teamName?: Prisma.StringFieldUpdateOperationsInput | string
  prize?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournament?: Prisma.TournamentUpdateOneRequiredWithoutPositionsNestedInput
}

export type TournamentPositionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  teamName?: Prisma.StringFieldUpdateOperationsInput | string
  prize?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPositionCreateManyInput = {
  id?: string
  tournamentId: string
  position: number
  teamName: string
  prize?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentPositionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  teamName?: Prisma.StringFieldUpdateOperationsInput | string
  prize?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPositionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  teamName?: Prisma.StringFieldUpdateOperationsInput | string
  prize?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPositionListRelationFilter = {
  every?: Prisma.TournamentPositionWhereInput
  some?: Prisma.TournamentPositionWhereInput
  none?: Prisma.TournamentPositionWhereInput
}

export type TournamentPositionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TournamentPositionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  teamName?: Prisma.SortOrder
  prize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentPositionAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
  prize?: Prisma.SortOrder
}

export type TournamentPositionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  teamName?: Prisma.SortOrder
  prize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentPositionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  teamName?: Prisma.SortOrder
  prize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentPositionSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
  prize?: Prisma.SortOrder
}

export type TournamentPositionCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TournamentPositionCreateWithoutTournamentInput, Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput> | Prisma.TournamentPositionCreateWithoutTournamentInput[] | Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput | Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TournamentPositionCreateManyTournamentInputEnvelope
  connect?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
}

export type TournamentPositionUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TournamentPositionCreateWithoutTournamentInput, Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput> | Prisma.TournamentPositionCreateWithoutTournamentInput[] | Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput | Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TournamentPositionCreateManyTournamentInputEnvelope
  connect?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
}

export type TournamentPositionUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPositionCreateWithoutTournamentInput, Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput> | Prisma.TournamentPositionCreateWithoutTournamentInput[] | Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput | Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TournamentPositionUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TournamentPositionUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TournamentPositionCreateManyTournamentInputEnvelope
  set?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  disconnect?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  delete?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  connect?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  update?: Prisma.TournamentPositionUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TournamentPositionUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TournamentPositionUpdateManyWithWhereWithoutTournamentInput | Prisma.TournamentPositionUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TournamentPositionScalarWhereInput | Prisma.TournamentPositionScalarWhereInput[]
}

export type TournamentPositionUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPositionCreateWithoutTournamentInput, Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput> | Prisma.TournamentPositionCreateWithoutTournamentInput[] | Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput | Prisma.TournamentPositionCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TournamentPositionUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TournamentPositionUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TournamentPositionCreateManyTournamentInputEnvelope
  set?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  disconnect?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  delete?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  connect?: Prisma.TournamentPositionWhereUniqueInput | Prisma.TournamentPositionWhereUniqueInput[]
  update?: Prisma.TournamentPositionUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TournamentPositionUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TournamentPositionUpdateManyWithWhereWithoutTournamentInput | Prisma.TournamentPositionUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TournamentPositionScalarWhereInput | Prisma.TournamentPositionScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type TournamentPositionCreateWithoutTournamentInput = {
  id?: string
  position: number
  teamName: string
  prize?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentPositionUncheckedCreateWithoutTournamentInput = {
  id?: string
  position: number
  teamName: string
  prize?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentPositionCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TournamentPositionWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentPositionCreateWithoutTournamentInput, Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput>
}

export type TournamentPositionCreateManyTournamentInputEnvelope = {
  data: Prisma.TournamentPositionCreateManyTournamentInput | Prisma.TournamentPositionCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type TournamentPositionUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TournamentPositionWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentPositionUpdateWithoutTournamentInput, Prisma.TournamentPositionUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TournamentPositionCreateWithoutTournamentInput, Prisma.TournamentPositionUncheckedCreateWithoutTournamentInput>
}

export type TournamentPositionUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TournamentPositionWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentPositionUpdateWithoutTournamentInput, Prisma.TournamentPositionUncheckedUpdateWithoutTournamentInput>
}

export type TournamentPositionUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.TournamentPositionScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentPositionUpdateManyMutationInput, Prisma.TournamentPositionUncheckedUpdateManyWithoutTournamentInput>
}

export type TournamentPositionScalarWhereInput = {
  AND?: Prisma.TournamentPositionScalarWhereInput | Prisma.TournamentPositionScalarWhereInput[]
  OR?: Prisma.TournamentPositionScalarWhereInput[]
  NOT?: Prisma.TournamentPositionScalarWhereInput | Prisma.TournamentPositionScalarWhereInput[]
  id?: Prisma.StringFilter<"TournamentPosition"> | string
  tournamentId?: Prisma.StringFilter<"TournamentPosition"> | string
  position?: Prisma.IntFilter<"TournamentPosition"> | number
  teamName?: Prisma.StringFilter<"TournamentPosition"> | string
  prize?: Prisma.FloatFilter<"TournamentPosition"> | number
  createdAt?: Prisma.DateTimeFilter<"TournamentPosition"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentPosition"> | Date | string
}

export type TournamentPositionCreateManyTournamentInput = {
  id?: string
  position: number
  teamName: string
  prize?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentPositionUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  teamName?: Prisma.StringFieldUpdateOperationsInput | string
  prize?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPositionUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  teamName?: Prisma.StringFieldUpdateOperationsInput | string
  prize?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPositionUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  teamName?: Prisma.StringFieldUpdateOperationsInput | string
  prize?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TournamentPositionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  position?: boolean
  teamName?: boolean
  prize?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentPosition"]>

export type TournamentPositionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  position?: boolean
  teamName?: boolean
  prize?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentPosition"]>

export type TournamentPositionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  position?: boolean
  teamName?: boolean
  prize?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tournamentPosition"]>

export type TournamentPositionSelectScalar = {
  id?: boolean
  tournamentId?: boolean
  position?: boolean
  teamName?: boolean
  prize?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TournamentPositionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "position" | "teamName" | "prize" | "createdAt" | "updatedAt", ExtArgs["result"]["tournamentPosition"]>
export type TournamentPositionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}
export type TournamentPositionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}
export type TournamentPositionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
}

export type $TournamentPositionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TournamentPosition"
  objects: {
    tournament: Prisma.$TournamentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tournamentId: string
    position: number
    teamName: string
    prize: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tournamentPosition"]>
  composites: {}
}

export type TournamentPositionGetPayload<S extends boolean | null | undefined | TournamentPositionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload, S>

export type TournamentPositionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentPositionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TournamentPositionCountAggregateInputType | true
  }

export interface TournamentPositionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TournamentPosition'], meta: { name: 'TournamentPosition' } }
  /**
   * Find zero or one TournamentPosition that matches the filter.
   * @param {TournamentPositionFindUniqueArgs} args - Arguments to find a TournamentPosition
   * @example
   * // Get one TournamentPosition
   * const tournamentPosition = await prisma.tournamentPosition.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentPositionFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentPositionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TournamentPosition that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentPositionFindUniqueOrThrowArgs} args - Arguments to find a TournamentPosition
   * @example
   * // Get one TournamentPosition
   * const tournamentPosition = await prisma.tournamentPosition.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentPositionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentPositionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentPosition that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPositionFindFirstArgs} args - Arguments to find a TournamentPosition
   * @example
   * // Get one TournamentPosition
   * const tournamentPosition = await prisma.tournamentPosition.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentPositionFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentPositionFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentPosition that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPositionFindFirstOrThrowArgs} args - Arguments to find a TournamentPosition
   * @example
   * // Get one TournamentPosition
   * const tournamentPosition = await prisma.tournamentPosition.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentPositionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentPositionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TournamentPositions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPositionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TournamentPositions
   * const tournamentPositions = await prisma.tournamentPosition.findMany()
   * 
   * // Get first 10 TournamentPositions
   * const tournamentPositions = await prisma.tournamentPosition.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentPositionWithIdOnly = await prisma.tournamentPosition.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentPositionFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentPositionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TournamentPosition.
   * @param {TournamentPositionCreateArgs} args - Arguments to create a TournamentPosition.
   * @example
   * // Create one TournamentPosition
   * const TournamentPosition = await prisma.tournamentPosition.create({
   *   data: {
   *     // ... data to create a TournamentPosition
   *   }
   * })
   * 
   */
  create<T extends TournamentPositionCreateArgs>(args: Prisma.SelectSubset<T, TournamentPositionCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TournamentPositions.
   * @param {TournamentPositionCreateManyArgs} args - Arguments to create many TournamentPositions.
   * @example
   * // Create many TournamentPositions
   * const tournamentPosition = await prisma.tournamentPosition.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentPositionCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentPositionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TournamentPositions and returns the data saved in the database.
   * @param {TournamentPositionCreateManyAndReturnArgs} args - Arguments to create many TournamentPositions.
   * @example
   * // Create many TournamentPositions
   * const tournamentPosition = await prisma.tournamentPosition.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TournamentPositions and only return the `id`
   * const tournamentPositionWithIdOnly = await prisma.tournamentPosition.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentPositionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentPositionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TournamentPosition.
   * @param {TournamentPositionDeleteArgs} args - Arguments to delete one TournamentPosition.
   * @example
   * // Delete one TournamentPosition
   * const TournamentPosition = await prisma.tournamentPosition.delete({
   *   where: {
   *     // ... filter to delete one TournamentPosition
   *   }
   * })
   * 
   */
  delete<T extends TournamentPositionDeleteArgs>(args: Prisma.SelectSubset<T, TournamentPositionDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TournamentPosition.
   * @param {TournamentPositionUpdateArgs} args - Arguments to update one TournamentPosition.
   * @example
   * // Update one TournamentPosition
   * const tournamentPosition = await prisma.tournamentPosition.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentPositionUpdateArgs>(args: Prisma.SelectSubset<T, TournamentPositionUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TournamentPositions.
   * @param {TournamentPositionDeleteManyArgs} args - Arguments to filter TournamentPositions to delete.
   * @example
   * // Delete a few TournamentPositions
   * const { count } = await prisma.tournamentPosition.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentPositionDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentPositionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPositionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TournamentPositions
   * const tournamentPosition = await prisma.tournamentPosition.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentPositionUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentPositionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentPositions and returns the data updated in the database.
   * @param {TournamentPositionUpdateManyAndReturnArgs} args - Arguments to update many TournamentPositions.
   * @example
   * // Update many TournamentPositions
   * const tournamentPosition = await prisma.tournamentPosition.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TournamentPositions and only return the `id`
   * const tournamentPositionWithIdOnly = await prisma.tournamentPosition.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentPositionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentPositionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TournamentPosition.
   * @param {TournamentPositionUpsertArgs} args - Arguments to update or create a TournamentPosition.
   * @example
   * // Update or create a TournamentPosition
   * const tournamentPosition = await prisma.tournamentPosition.upsert({
   *   create: {
   *     // ... data to create a TournamentPosition
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TournamentPosition we want to update
   *   }
   * })
   */
  upsert<T extends TournamentPositionUpsertArgs>(args: Prisma.SelectSubset<T, TournamentPositionUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentPositionClient<runtime.Types.Result.GetResult<Prisma.$TournamentPositionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TournamentPositions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPositionCountArgs} args - Arguments to filter TournamentPositions to count.
   * @example
   * // Count the number of TournamentPositions
   * const count = await prisma.tournamentPosition.count({
   *   where: {
   *     // ... the filter for the TournamentPositions we want to count
   *   }
   * })
  **/
  count<T extends TournamentPositionCountArgs>(
    args?: Prisma.Subset<T, TournamentPositionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentPositionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TournamentPosition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPositionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentPositionAggregateArgs>(args: Prisma.Subset<T, TournamentPositionAggregateArgs>): Prisma.PrismaPromise<GetTournamentPositionAggregateType<T>>

  /**
   * Group by TournamentPosition.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPositionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentPositionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentPositionGroupByArgs['orderBy'] }
      : { orderBy?: TournamentPositionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentPositionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentPositionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TournamentPosition model
 */
readonly fields: TournamentPositionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TournamentPosition.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentPositionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tournament<T extends Prisma.TournamentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TournamentPosition model
 */
export interface TournamentPositionFieldRefs {
  readonly id: Prisma.FieldRef<"TournamentPosition", 'String'>
  readonly tournamentId: Prisma.FieldRef<"TournamentPosition", 'String'>
  readonly position: Prisma.FieldRef<"TournamentPosition", 'Int'>
  readonly teamName: Prisma.FieldRef<"TournamentPosition", 'String'>
  readonly prize: Prisma.FieldRef<"TournamentPosition", 'Float'>
  readonly createdAt: Prisma.FieldRef<"TournamentPosition", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TournamentPosition", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TournamentPosition findUnique
 */
export type TournamentPositionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPosition to fetch.
   */
  where: Prisma.TournamentPositionWhereUniqueInput
}

/**
 * TournamentPosition findUniqueOrThrow
 */
export type TournamentPositionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPosition to fetch.
   */
  where: Prisma.TournamentPositionWhereUniqueInput
}

/**
 * TournamentPosition findFirst
 */
export type TournamentPositionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPosition to fetch.
   */
  where?: Prisma.TournamentPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPositions to fetch.
   */
  orderBy?: Prisma.TournamentPositionOrderByWithRelationInput | Prisma.TournamentPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentPositions.
   */
  cursor?: Prisma.TournamentPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentPositions.
   */
  distinct?: Prisma.TournamentPositionScalarFieldEnum | Prisma.TournamentPositionScalarFieldEnum[]
}

/**
 * TournamentPosition findFirstOrThrow
 */
export type TournamentPositionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPosition to fetch.
   */
  where?: Prisma.TournamentPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPositions to fetch.
   */
  orderBy?: Prisma.TournamentPositionOrderByWithRelationInput | Prisma.TournamentPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentPositions.
   */
  cursor?: Prisma.TournamentPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPositions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentPositions.
   */
  distinct?: Prisma.TournamentPositionScalarFieldEnum | Prisma.TournamentPositionScalarFieldEnum[]
}

/**
 * TournamentPosition findMany
 */
export type TournamentPositionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPositions to fetch.
   */
  where?: Prisma.TournamentPositionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPositions to fetch.
   */
  orderBy?: Prisma.TournamentPositionOrderByWithRelationInput | Prisma.TournamentPositionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TournamentPositions.
   */
  cursor?: Prisma.TournamentPositionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPositions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPositions.
   */
  skip?: number
  distinct?: Prisma.TournamentPositionScalarFieldEnum | Prisma.TournamentPositionScalarFieldEnum[]
}

/**
 * TournamentPosition create
 */
export type TournamentPositionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * The data needed to create a TournamentPosition.
   */
  data: Prisma.XOR<Prisma.TournamentPositionCreateInput, Prisma.TournamentPositionUncheckedCreateInput>
}

/**
 * TournamentPosition createMany
 */
export type TournamentPositionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TournamentPositions.
   */
  data: Prisma.TournamentPositionCreateManyInput | Prisma.TournamentPositionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TournamentPosition createManyAndReturn
 */
export type TournamentPositionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * The data used to create many TournamentPositions.
   */
  data: Prisma.TournamentPositionCreateManyInput | Prisma.TournamentPositionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentPosition update
 */
export type TournamentPositionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * The data needed to update a TournamentPosition.
   */
  data: Prisma.XOR<Prisma.TournamentPositionUpdateInput, Prisma.TournamentPositionUncheckedUpdateInput>
  /**
   * Choose, which TournamentPosition to update.
   */
  where: Prisma.TournamentPositionWhereUniqueInput
}

/**
 * TournamentPosition updateMany
 */
export type TournamentPositionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TournamentPositions.
   */
  data: Prisma.XOR<Prisma.TournamentPositionUpdateManyMutationInput, Prisma.TournamentPositionUncheckedUpdateManyInput>
  /**
   * Filter which TournamentPositions to update
   */
  where?: Prisma.TournamentPositionWhereInput
  /**
   * Limit how many TournamentPositions to update.
   */
  limit?: number
}

/**
 * TournamentPosition updateManyAndReturn
 */
export type TournamentPositionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * The data used to update TournamentPositions.
   */
  data: Prisma.XOR<Prisma.TournamentPositionUpdateManyMutationInput, Prisma.TournamentPositionUncheckedUpdateManyInput>
  /**
   * Filter which TournamentPositions to update
   */
  where?: Prisma.TournamentPositionWhereInput
  /**
   * Limit how many TournamentPositions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentPosition upsert
 */
export type TournamentPositionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * The filter to search for the TournamentPosition to update in case it exists.
   */
  where: Prisma.TournamentPositionWhereUniqueInput
  /**
   * In case the TournamentPosition found by the `where` argument doesn't exist, create a new TournamentPosition with this data.
   */
  create: Prisma.XOR<Prisma.TournamentPositionCreateInput, Prisma.TournamentPositionUncheckedCreateInput>
  /**
   * In case the TournamentPosition was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentPositionUpdateInput, Prisma.TournamentPositionUncheckedUpdateInput>
}

/**
 * TournamentPosition delete
 */
export type TournamentPositionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
  /**
   * Filter which TournamentPosition to delete.
   */
  where: Prisma.TournamentPositionWhereUniqueInput
}

/**
 * TournamentPosition deleteMany
 */
export type TournamentPositionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentPositions to delete
   */
  where?: Prisma.TournamentPositionWhereInput
  /**
   * Limit how many TournamentPositions to delete.
   */
  limit?: number
}

/**
 * TournamentPosition without action
 */
export type TournamentPositionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPosition
   */
  select?: Prisma.TournamentPositionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPosition
   */
  omit?: Prisma.TournamentPositionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPositionInclude<ExtArgs> | null
}
